#
# Ensure you replace the insecure_password by the secure one before deploy
#

version: '3.1'

services:
  postgres:
    image: postgres:alpine3.17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: sveltekit-cms
      POSTGRES_PASSWORD: insecure_password
      POSTGRES_USER: root
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  # redis for caching user session and pub/sub for background tasks such as mailling service
  redis:
    image: redis:6-alpine3.17
    container_name: redis
    restart: always
    ports:
      - 6378:6378
    command: redis-server --requirepass insecure_password
    extra_hosts:
      - 'host.docker.internal:host-gateway'
